title: Kasun Gamlath
author: Kasun Gamlath
email: kasun.smu@gmail.com
description: >-
  Photography Portfolio.
greeting: Thank you for visiting my photography portfolio.

social:
  # twitter: joaomlneto
  # facebook: joaomlneto
  instagram: _kasung
  email: kasungamlath.ca@gmail.com
  # github: joaomlneto
  # linkedin:

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true
