title: Kasun Gamlath Photography
author: Kasun Gamlath
email: kasun.smu@gmail.com
description: >-
  Photography portfolio.

social:
  # twitter: joaomlneto
  # facebook: joaomlneto
  instagram: _kasung
  # github: joaomlneto
  # linkedin:

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true
